# Прозрачность активного (фокусного) окна (95%)
active-opacity = 0.85;

# Прозрачность неактивных окон на заднем плане (85%)
inactive-opacity = 0.85;

# Настройка размытия (blur), чтобы текст на заднем плане не сливался
blur: {
  method = "dual_kawase";
  strength = 3;
};

# Исключения (какие приложения НЕ должны быть прозрачными, например игры или браузер)
opacity-rule = [
  "100:class_g = 'Firefox'",
  "100:class_g = 'chromium'",
  "100:class_g = 'mpv'"
];

# Использовать ускорение видеокарты для плавной работы
backend = "glx";
vsync = true;
